version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8080:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/media1tbx/current/reactjs/portfolio_server/media:/usr/share/nginx/html/media
      - /mnt/media1tbx/current/reactjs/portfolio_server/icons:/usr/share/nginx/html/icons
    ports:
      - "8081:80"
