version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    networks:
      - portfolio_server_custom_network
    ports:
      - "8082:80"

networks:
  portfolio_server_custom_network:
    external: true
